### ISSUE TITLE
Can't download 50M or bigger file with iBridges CLI function

### ISSUE THREAD

**Issue by jnimoth** [UtrechtUniversity/iBridges#126]
**Describe the bug**
If I try do download files from iRODS to my local environment using the CLI function of iBridges, I get an error message and a file with 0 byte size is created locally.

**To Reproduce**
```
# Start with empty loca dir
(ibridges_venv_1) [user@login1 user]$ ls /scratch/user/downloaded/

# This is the content on the iRODS side
(ibridges_venv_1) [user@login1 user]$ ibridges list irods:/testrug/home/user/ibridges_test_irods/
/testrug/home/user/ibridges_test_irods:
  /testrug/home/user/ibridges_test_irods/100MB_Testfile
  /testrug/home/user/ibridges_test_irods/1GB_File
  /testrug/home/user/ibridges_test_irods/250MB_Testfile
  /testrug/home/user/ibridges_test_irods/500MB_Testfile
  /testrug/home/user/ibridges_test_irods/50MB_Testfile

# Now try to download a file from the iRODS side to local via 'ibridges download'
(ibridges_venv_1) [user@login1 user]$ ibridges download irods:/testrug/home/user/ibridges_test_irods/50MB_Testfile /scratch/user/downloaded/
Traceback (most recent call last):
  File "/home2/user/.venv/ibridges_venv_1/bin/ibridges", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home2/user/.venv/ibridges_venv_1/lib64/python3.11/site-packages/ibridges/__main__.py", line 67, in main
    ibridges_download()
  File "/home2/user/.venv/ibridges_venv_1/lib64/python3.11/site-packages/ibridges/__main__.py", line 214, in ibridges_download
    download(session,
  File "/home2/user/.venv/ibridges_venv_1/lib64/python3.11/site-packages/ibridges/data_operations.py", line 414, in download
    _obj_get(session, irods_path, local_path, overwrite, resc_name, options)
  File "/home2/user/.venv/ibridges_venv_1/lib64/python3.11/site-packages/ibridges/data_operations.py", line 202, in _obj_get
    session.irods_session.data_objects.get(str(irods_path), local_path, **options)
  File "/home2/user/.venv/ibridges_venv_1/lib64/python3.11/site-packages/irods/manager/data_object_manager.py", line 165, in get
    self._download(path, local_path, num_threads = num_threads, **options)
  File "/home2/user/.venv/ibridges_venv_1/lib64/python3.11/site-packages/irods/manager/data_object_manager.py", line 145, in _download
    if not self.parallel_get( (obj,o), local_path, num_threads = num_threads,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home2/user/.venv/ibridges_venv_1/lib64/python3.11/site-packages/irods/manager/data_object_manager.py", line 269, in parallel_get
    return parallel.io_main( self.sess, data_or_path_, parallel.Oper.GET | (parallel.Oper.NONBLOCKING if async_ else 0), file_,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home2/user/.venv/ibridges_venv_1/lib64/python3.11/site-packages/irods/parallel.py", line 469, in io_main
    retval = _io_multipart_threaded (Operation, (Data, Io), replica_token, resc_hier, session, fname, total_bytes,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home2/user/.venv/ibridges_venv_1/lib64/python3.11/site-packages/irods/parallel.py", line 357, in _io_multipart_threaded
    File = gen_file_handle()
           ^^^^^^^^^^^^^^^^^
  File "/home2/user/.venv/ibridges_venv_1/lib64/python3.11/site-packages/irods/parallel.py", line 356, in <lambda>
    gen_file_handle = lambda: open(fname, Operation.disk_file_mode(initial_open = (counter == 1)))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IsADirectoryError: [Errno 21] Is a directory: '/scratch/user/downloaded'
(ibridges_venv_1) [user@login1 user]$ ls /scratch/user/downloaded/
50MB_Testfile
(ibridges_venv_1) [user@login1 user]$ ls -l /scratch/user/downloaded/
total 0
-rw-rw-r--. 1 user user 0 Apr 25 12:16 50MB_Testfile
```

**Expected behavior**
Files get downloaded from iRODS to local.

**Provide some information:**
 - OS: Linux (Rocky)
 - Software version or branch you are working on:  0.1.4 (installed via pip)
 - python version: 3.11
 - iRODS version: 4.2.11
 - python-irodsclient version (`python -c "import irods; print(irods.__version__)"` ): 2.0.0

**Comment by qubixes** [comment]
Hi @jnimoth,

I'm trying to reproduce it locally, but no luck so far (same versions, except the iRODS server). The question is where the actual problem lies. Have you tried the same thing with the iBridges API as well?

Perhaps you can try to see if you use the python-irodsclient directly (in an interactive python):

```python
from ibridges.interactive import interactive_auth

session = interactive_auth()
session.irods_session.data_objects.get("/testrug/home/user/ibridges_test_irods/50MB_Testfile", "/scratch/user/downloaded/")
```

**Comment by jnimoth** [comment]
Hi,
I just tried again via the ibridges API, I get also errors with it:

```
>>> session.irods_session.data_objects.get("/testrug/home/user/ibridges_test_irods/50MB_Testfile", "/scratch/user/downloaded/")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home2/user/.venv/ibridges_venv_1/lib64/python3.11/site-packages/irods/manager/data_object_manager.py", line 165, in get
    self._download(path, local_path, num_threads = num_threads, **options)
  File "/home2/user/.venv/ibridges_venv_1/lib64/python3.11/site-packages/irods/manager/data_object_manager.py", line 145, in _download
    if not self.parallel_get( (obj,o), local_path, num_threads = num_threads,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home2/user/.venv/ibridges_venv_1/lib64/python3.11/site-packages/irods/manager/data_object_manager.py", line 269, in parallel_get
    return parallel.io_main( self.sess, data_or_path_, parallel.Oper.GET | (parallel.Oper.NONBLOCKING if async_ else 0), file_,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home2/user/.venv/ibridges_venv_1/lib64/python3.11/site-packages/irods/parallel.py", line 469, in io_main
    retval = _io_multipart_threaded (Operation, (Data, Io), replica_token, resc_hier, session, fname, total_bytes,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home2/user/.venv/ibridges_venv_1/lib64/python3.11/site-packages/irods/parallel.py", line 357, in _io_multipart_threaded
    File = gen_file_handle()
           ^^^^^^^^^^^^^^^^^
  File "/home2/user/.venv/ibridges_venv_1/lib64/python3.11/site-packages/irods/parallel.py", line 356, in <lambda>
    gen_file_handle = lambda: open(fname, Operation.disk_file_mode(initial_open = (counter == 1)))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IsADirectoryError: [Errno 21] Is a directory: '/scratch/user/downloaded/'
```

I then also tried to download a file again on another Linux machine (Ubuntu-based, Python 3.10, same ibridges version), and I  also see an error there:

```
$ ibridges download irods:/testrug/home/user/1GB_Testfile_1 /home/user/    
                                                
Traceback (most recent call last):
  File "/home/user/python_venvs/ibridges_new/bin/ibridges", line 8, in <module>
    sys.exit(main())
  File "/home/user/python_venvs/ibridges_new/lib/python3.10/site-packages/ibridges/__main__.py", line 67, in main
    ibridges_download()
  File "/home/user/python_venvs/ibridges_new/lib/python3.10/site-packages/ibridges/__main__.py", line 214, in ibridges_download
    download(session,
  File "/home/user/python_venvs/ibridges_new/lib/python3.10/site-packages/ibridges/data_operations.py", line 414, in download
    _obj_get(session, irods_path, local_path, overwrite, resc_name, options)
  File "/home/user/python_venvs/ibridges_new/lib/python3.10/site-packages/ibridges/data_operations.py", line 202, in _obj_get
    session.irods_session.data_objects.get(str(irods_path), local_path, **options)
  File "/home/user/python_venvs/ibridges_new/lib/python3.10/site-packages/irods/manager/data_object_manager.py", line 165, in get 
    self._download(path, local_path, num_threads = num_threads, **options)
  File "/home/user/python_venvs/ibridges_new/lib/python3.10/site-packages/irods/manager/data_object_manager.py", line 145, in _download
    if not self.parallel_get( (obj,o), local_path, num_threads = num_threads,
  File "/home/user/python_venvs/ibridges_new/lib/python3.10/site-packages/irods/manager/data_object_manager.py", line 269, in parallel_get
    return parallel.io_main( self.sess, data_or_path_, parallel.Oper.GET | (parallel.Oper.NONBLOCKING if async_ else 0), file_,
  File "/home/user/python_venvs/ibridges_new/lib/python3.10/site-packages/irods/parallel.py", line 469, in io_main
    retval = _io_multipart_threaded (Operation, (Data, Io), replica_token, resc_hier, session, fname, total_bytes,
  File "/home/user/python_venvs/ibridges_new/lib/python3.10/site-packages/irods/parallel.py", line 357, in _io_multipart_threaded
    File = gen_file_handle()
  File "/home/user/python_venvs/ibridges_new/lib/python3.10/site-packages/irods/parallel.py", line 356, in <lambda>
    gen_file_handle = lambda: open(fname, Operation.disk_file_mode(initial_open = (counter == 1)))
IsADirectoryError: [Errno 21] Is a directory: '/home/user'

```

**Comment by jnimoth** [comment]
The issue seems to just appear for files of a certain size. For example, I just tried a smaller file (~20 MB) which worked directly:

```
(ibridges_venv_1) [user@login1 ~]$ ibridges download irods:/testrug/home/user/ibridges_test_irods/20MB_Testfile /scratch/user/downloaded/

(ibridges_venv_1) [user@login1 ~]$ ls -l /scratch/user/downloaded/
total 16360
-rw-rw-r--. 1 user user 20000000 Apr 25 17:08 20MB_Testfile
```


When I go for a bigger file (now ~35 MB), I see again the error:

``` 
(ibridges_venv_1) [user@login1 ~]$ ibridges download irods:/testrug/home/user/ibridges_test_irods/35MB_Testfile /scratch/user/downloaded/
Traceback (most recent call last):
  File &quot;/home2/user/.venv/ibridges_venv_1/bin/ibridges&quot;, line 8, in &lt;module&gt;
    sys.exit(main())
             ^^^^^^
  File &quot;/home2/user/.venv/ibridges_venv_1/lib64/python3.11/site-packages/ibridges/__main__.py&quot;, line 67, in main
    ibridges_download()
  File &quot;/home2/user/.venv/ibridges_venv_1/lib64/python3.11/site-packages/ibridges/__main__.py&quot;, line 214, in ibridges_download
    download(session,
  File &quot;/home2/user/.venv/ibridges_venv_1/lib64/python3.11/site-packages/ibridges/data_operations.py&quot;, line 414, in download
    _obj_get(session, irods_path, local_path, overwrite, resc_name, options)
  File &quot;/home2/user/.venv/ibridges_venv_1/lib64/python3.11/site-packages/ibridges/data_operations.py&quot;, line 202, in _obj_get
    session.irods_session.data_objects.get(str(irods_path), local_path, **options)
  File &quot;/home2/user/.venv/ibridges_venv_1/lib64/python3.11/site-packages/irods/manager/data_object_manager.py&quot;, line 165, in get
    self._download(path, local_path, num_threads = num_threads, **options)
  File &quot;/home2/user/.venv/ibridges_venv_1/lib64/python3.11/site-packages/irods/manager/data_object_manager.py&quot;, line 145, in _download
    if not self.parallel_get( (obj,o), local_path, num_threads = num_threads,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File &quot;/home2/user/.venv/ibridges_venv_1/lib64/python3.11/site-packages/irods/manager/data_object_manager.py&quot;, line 269, in parallel_get
    return parallel.io_main( self.sess, data_or_path_, parallel.Oper.GET | (parallel.Oper.NONBLOCKING if async_ else 0), file_,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File &quot;/home2/user/.venv/ibridges_venv_1/lib64/python3.11/site-packages/irods/parallel.py&quot;, line 469, in io_main
    retval = _io_multipart_threaded (Operation, (Data, Io), replica_token, resc_hier, session, fname, total_bytes,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File &quot;/home2/user/.venv/ibridges_venv_1/lib64/python3.11/site-packages/irods/parallel.py&quot;, line 357, in _io_multipart_threaded
    File = gen_file_handle()
           ^^^^^^^^^^^^^^^^^
  File &quot;/home2/user/.venv/ibridges_venv_1/lib64/python3.11/site-packages/irods/parallel.py&quot;, line 356, in &lt;lambda&gt;
    gen_file_handle = lambda: open(fname, Operation.disk_file_mode(initial_open = (counter == 1)))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IsADirectoryError: [Errno 21] Is a directory: &apos;/scratch/user/downloaded&apos;
(ibridges_venv_1) [user@login1 ~]$ ls -l /scratch/user/downloaded/
total 19532
-rw-rw-r--. 1 user user 20000000 Apr 25 17:08 20MB_Testfile
-rw-rw-r--. 1 user user        0 Apr 25 17:08 35MB_Testfile
```

Maybe it should be also mentioned that the other way around, so uploading via `ibridges upload ...` works without any issue. This is also true when the files are bigger (tested up to 1GB).

**Comment by chStaiger** [comment]
We found the bug in the python-irodsclient:
https://github.com/irods/python-irodsclient/issues/543

Work around for now is to define a distinct file location for  larger files rather than a destination folder.

**Comment by chStaiger** [comment]
I created a temporary quick fix in the branch 126-workaround. Can you please let us know if that fixes your issue?

```
pip install git+https://github.com/UtrechtUniversity/iBridges.git@126-workaround
```

**Comment by jnimoth** [comment]
Hi Christine,
I  can confirm that the downloads now work with the provided fix! Thanks!
