### ISSUE TITLE
ibridges init crashes when .irodsA file is outdated

### ISSUE THREAD

**Issue by maartenschermer** [UtrechtUniversity/iBridges#132]
ibridges init crashes when the .irodsA file is present but outdated. stacktrace below.

```
$ ibridges init ~/.irods/irods_env_its.json 
/home/maarten/.irods/irods_env_its.json /home/maarten/.irods/irods_env_its.json
Traceback (most recent call last):
  File "/home/maarten/anaconda3/envs/cwl/lib/python3.9/site-packages/irods/session.py", line 290, in server_version
    return tuple(ast.literal_eval(reported_vsn))
  File "/home/maarten/anaconda3/envs/cwl/lib/python3.9/ast.py", line 62, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/home/maarten/anaconda3/envs/cwl/lib/python3.9/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 0
    
SyntaxError: unexpected EOF while parsing

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/maarten/anaconda3/envs/cwl/lib/python3.9/site-packages/irods/session.py", line 296, in __server_version
    conn = next(iter(self.pool.active))
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/maarten/anaconda3/envs/cwl/lib/python3.9/site-packages/irods/pool.py", line 62, in get_connection
    conn = self.idle.pop()
KeyError: 'pop from an empty set'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/maarten/anaconda3/envs/cwl/lib/python3.9/site-packages/ibridges/session.py", line 190, in authenticate_using_auth_file
    _ = irods_session.server_version
  File "/home/maarten/anaconda3/envs/cwl/lib/python3.9/site-packages/irods/session.py", line 292, in server_version
    return self.__server_version()
  File "/home/maarten/anaconda3/envs/cwl/lib/python3.9/site-packages/irods/session.py", line 299, in __server_version
    conn = self.pool.get_connection()
  File "/home/maarten/anaconda3/envs/cwl/lib/python3.9/site-packages/irods/pool.py", line 17, in method_
    ret = method(self,*s,**kw)
  File "/home/maarten/anaconda3/envs/cwl/lib/python3.9/site-packages/irods/pool.py", line 78, in get_connection
    conn = Connection(self, self.account)
  File "/home/maarten/anaconda3/envs/cwl/lib/python3.9/site-packages/irods/connection.py", line 88, in __init__
    self._login_pam()
  File "/home/maarten/anaconda3/envs/cwl/lib/python3.9/site-packages/irods/connection.py", line 476, in _login_pam
    raise exc
  File "/home/maarten/anaconda3/envs/cwl/lib/python3.9/site-packages/irods/connection.py", line 469, in _login_pam
    self._login_native()
  File "/home/maarten/anaconda3/envs/cwl/lib/python3.9/site-packages/irods/connection.py", line 616, in _login_native
    self.recv()
  File "/home/maarten/anaconda3/envs/cwl/lib/python3.9/site-packages/irods/connection.py", line 152, in recv
    raise get_exception_by_code(msg.int_info, err_msg)
irods.exception.CAT_INVALID_USER: None

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/maarten/anaconda3/envs/cwl/bin/ibridges", line 8, in <module>
    sys.exit(main())
  File "/home/maarten/anaconda3/envs/cwl/lib/python3.9/site-packages/ibridges/__main__.py", line 73, in main
    ibridges_init()
  File "/home/maarten/anaconda3/envs/cwl/lib/python3.9/site-packages/ibridges/__main__.py", line 125, in ibridges_init
    with interactive_auth(irods_env_path=ienv_path) as session:
  File "/home/maarten/anaconda3/envs/cwl/lib/python3.9/site-packages/ibridges/interactive.py", line 46, in interactive_auth
    session = _from_pw_file(irods_env_path)
  File "/home/maarten/anaconda3/envs/cwl/lib/python3.9/site-packages/ibridges/interactive.py", line 72, in _from_pw_file
    session = Session(irods_env_path)
  File "/home/maarten/anaconda3/envs/cwl/lib/python3.9/site-packages/ibridges/session.py", line 67, in __init__
    self.irods_session = self.connect()
  File "/home/maarten/anaconda3/envs/cwl/lib/python3.9/site-packages/ibridges/session.py", line 156, in connect
    return self.authenticate_using_auth_file()
  File "/home/maarten/anaconda3/envs/cwl/lib/python3.9/site-packages/ibridges/session.py", line 194, in authenticate_using_auth_file
    raise _translate_irods_error(e) from e
ibridges.session.LoginError: User credentials are not accepted
```

**Comment by chStaiger** [comment]
Can you test whether the bug still occurrs in the latest release please?

**Comment by chStaiger** [comment]
Close for now.
