### ISSUE TITLE
Syncing with invalid paths throws obscure error

### ISSUE THREAD

**Issue by dometto** [UtrechtUniversity/iBridges#157]
Trying to sync my irods home to a random directory fails. This may be expected as the paths don't match (irods home is `<bla>/research-test-dawa`, target is `/tmp`). But for some reason this throws a network-related error, which seems unhelpful to the user:

```
 $ ibridges sync irods:~/ /tmp/ 

Traceback (most recent call last):
  File "/opt/homebrew/bin/ibridges", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/ibridges/__main__.py", line 76, in main
    ibridges_sync()
  File "/opt/homebrew/lib/python3.11/site-packages/ibridges/__main__.py", line 315, in ibridges_sync
    sync_data(session,
  File "/opt/homebrew/lib/python3.11/site-packages/ibridges/sync.py", line 159, in sync_data
    tgt_files, tgt_folders=_get_local_tree(
                           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/ibridges/sync.py", line 234, in _get_local_tree
    checksum=_calc_checksum(full_path)))
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/ibridges/sync.py", line 210, in _calc_checksum
    with open(filepath, 'rb', buffering=0) as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 102] Operation not supported on socket: '/tmp/com.apple.launchd.V2EF9B0wEo/Listeners'
```

**Comment by qubixes** [comment]
@dometto Thanks for the report. I feel like this is something specific to the /tmp directory. if you create /tmp/ibridges and sync to that location, do you get the same error?

**Comment by chStaiger** [comment]
I tried it on my mac and I get a Permission error:

```
staig001@busoni iBridges % ibridges sync irods:~/ /tmp
Traceback (most recent call last):
  File "/opt/homebrew/bin/ibridges", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.10/site-packages/ibridges/__main__.py", line 77, in main
    ibridges_sync()
  File "/opt/homebrew/lib/python3.10/site-packages/ibridges/__main__.py", line 316, in ibridges_sync
    sync_data(session,
  File "/opt/homebrew/lib/python3.10/site-packages/ibridges/sync.py", line 158, in sync_data
    tgt_files, tgt_folders=_get_local_tree(
  File "/opt/homebrew/lib/python3.10/site-packages/ibridges/sync.py", line 233, in _get_local_tree
    checksum=_calc_checksum(full_path)))
  File "/opt/homebrew/lib/python3.10/site-packages/ibridges/sync.py", line 209, in _calc_checksum
    with open(filepath, 'rb', buffering=0) as file:
PermissionError: [Errno 13] Permission denied: '/tmp/ticket-FgMoX8'
```

One needs to have sufficient rights to all items in the local folder to calculate the differences and do the update.

This will work and will take a looooooong time:
```
staig001@busoni iBridges % mkdir /tmp/backup_irods
staig001@busoni iBridges % ibridges sync irods:~/ /tmp/backup_irods
```

**Comment by dometto** [comment]
Ah yes, I see now that the networking error in my case was specific to the socket files in `/tmp`. 👍 Thanks for #158 @qubixes!
