### ISSUE TITLE
Passing `.` as source directory throws error

### ISSUE THREAD

**Issue by dometto** [UtrechtUniversity/iBridges#167]
Steps to reproduce:

1. `mkdir test`
2. `cd test`
3. `touch bla`
4. `ibridges sync . irods:~/`

Result:

```
Uploading: 0it [00:00, ?it/s]Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/ibridges/sync.py", line 323, in _copy_local_to_irods
    upload(session=session,
  File "/opt/homebrew/lib/python3.11/site-packages/ibridges/data_operations.py", line 394, in upload
    raise FileNotFoundError(f"Cannot find local file '{local_path}', check the path.")
FileNotFoundError: Cannot find local file 'la', check the path.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/bin/ibridges", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/ibridges/__main__.py", line 76, in main
    ibridges_sync()
  File "/opt/homebrew/lib/python3.11/site-packages/ibridges/__main__.py", line 315, in ibridges_sync
    sync_data(session,
  File "/opt/homebrew/lib/python3.11/site-packages/ibridges/sync.py", line 178, in sync_data
    _copy_local_to_irods(
  File "/opt/homebrew/lib/python3.11/site-packages/ibridges/sync.py", line 336, in _copy_local_to_irods
    raise ValueError(f"Uploading '{source_path}' failed: {repr(err)}") from err
ValueError: Uploading 'la' failed: FileNotFoundError("Cannot find local file 'la', check the path.")
Uploading: 0it [00:00, ?it/s]
```

So passing `.` as the source location somehow causes iBridges to look for file `la` instead of `bla`.

Same happens when passing `./`.

(Of course it is also ok if `.` is not supported, but then a sane error should be thrown. :-))

**Comment by qubixes** [comment]
@dometto This was fixed when rewriting the sync functionality. I can reproduce the error in the previous version, but the latest development branch I get the expected behavior. I will close this issue for now, if the issue pops up again, you can reopen this issue.
