### ISSUE TITLE
Issues with large files -- asynchronously calculate checksums

### ISSUE THREAD

**Issue by qubixes** [UtrechtUniversity/iBridges#185]
I don't have reproduction exactly, but here is the description:

I was uploading large files to YoDa/iRods and the following happened:

The upload itself was correct, but I get an error (probably NetworkError) from the python irods client about the connection.
After immediately checking the checksum in another script, I also get an uncaught database error through the python-irodsclient. This all presumably happens because the checksum is not ready yet at the right time.

**Comment by chStaiger** [comment]
Most probably the `REG_CHECKSUM` which triggers to calculate the checksum of the file on the iRODS server and store it in the iCAT takes too long and you loose the connection to the server.

For really large files we need and asynchronous data transfer.

**Comment by qubixes** [comment]
```
CRITICAL:irods.connection:The read operation timed out
ERROR:irods.connection:Could not receive server response
Traceback (most recent call last):
  File "/home/qubix/.pyenv/versions/3.11.6/lib/python3.11/site-packages/irods/message/__init__.py", line 204, in _recv_message_in_len
    buf = sock.recv(size_left, socket.MSG_WAITALL)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qubix/.pyenv/versions/3.11.6/lib/python3.11/ssl.py", line 1293, in recv
    raise ValueError(
ValueError: non-zero flags not allowed in calls to recv() on <class 'ssl.SSLSocket'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qubix/.pyenv/versions/3.11.6/lib/python3.11/site-packages/irods/connection.py", line 133, in recv
    msg = iRODSMessage.recv(self.socket)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qubix/.pyenv/versions/3.11.6/lib/python3.11/site-packages/irods/message/__init__.py", line 294, in recv
    rsp_header_size = _recv_message_in_len(sock, 4)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qubix/.pyenv/versions/3.11.6/lib/python3.11/site-packages/irods/message/__init__.py", line 206, in _recv_message_in_len
    buf = sock.recv(size_left)
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/qubix/.pyenv/versions/3.11.6/lib/python3.11/ssl.py", line 1296, in recv
    return self.read(buflen)
           ^^^^^^^^^^^^^^^^^
  File "/home/qubix/.pyenv/versions/3.11.6/lib/python3.11/ssl.py", line 1169, in read
    return self._sslobj.read(len)
           ^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qubix/.pyenv/versions/3.11.6/bin/ibridges", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/qubix/Documents/repos/iBridges/ibridges/__main__.py", line 80, in main
    ibridges_upload()
  File "/home/qubix/Documents/repos/iBridges/ibridges/__main__.py", line 298, in ibridges_upload
    ops = upload(session,
          ^^^^^^^^^^^^^^^
  File "/home/qubix/Documents/repos/iBridges/ibridges/data_operations.py", line 173, in upload
    perform_operations(session, ops, ignore_err=ignore_err)
  File "/home/qubix/Documents/repos/iBridges/ibridges/data_operations.py", line 384, in perform_operations
    _obj_put(session, lpath, ipath, overwrite=True, ignore_err=ignore_err, options=options,
  File "/home/qubix/Documents/repos/iBridges/ibridges/data_operations.py", line 76, in _obj_put
    session.irods_session.data_objects.put(local_path, str(irods_path), **options)
  File "/home/qubix/.pyenv/versions/3.11.6/lib/python3.11/site-packages/irods/manager/data_object_manager.py", line 194, in put
    if not self.parallel_put( local_path, (obj,o), total_bytes = sizelist[0], num_threads = num_threads,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qubix/.pyenv/versions/3.11.6/lib/python3.11/site-packages/irods/manager/data_object_manager.py", line 289, in parallel_put
    return parallel.io_main( self.sess, data_or_path_, parallel.Oper.PUT | (parallel.Oper.NONBLOCKING if async_ else 0), file_,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qubix/.pyenv/versions/3.11.6/lib/python3.11/site-packages/irods/parallel.py", line 469, in io_main
    retval = _io_multipart_threaded (Operation, (Data, Io), replica_token, resc_hier, session, fname, total_bytes,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qubix/.pyenv/versions/3.11.6/lib/python3.11/site-packages/irods/parallel.py", line 379, in _io_multipart_threaded
    bytecounts = [ f.result() for f in futures ]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qubix/.pyenv/versions/3.11.6/lib/python3.11/site-packages/irods/parallel.py", line 379, in <listcomp>
    bytecounts = [ f.result() for f in futures ]
                   ^^^^^^^^^^
  File "/home/qubix/.pyenv/versions/3.11.6/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/qubix/.pyenv/versions/3.11.6/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/qubix/.pyenv/versions/3.11.6/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qubix/.pyenv/versions/3.11.6/lib/python3.11/site-packages/irods/parallel.py", line 318, in _io_part
    return ( _copy_part (file_, objHandle, length, queueObject, thread_debug_id, mgr_) if Operation.isPut()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qubix/.pyenv/versions/3.11.6/lib/python3.11/site-packages/irods/parallel.py", line 250, in _copy_part
    mgr.remove_io( obj_ ) # 1. closes obj if it is not the mgr's initial descriptor
    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/qubix/.pyenv/versions/3.11.6/lib/python3.11/site-packages/irods/parallel.py", line 298, in remove_io
    if is_initial: self.finalize()
                   ^^^^^^^^^^^^^^^
  File "/home/qubix/.pyenv/versions/3.11.6/lib/python3.11/site-packages/irods/parallel.py", line 301, in finalize
    self.initial_io.close()
  File "/home/qubix/.pyenv/versions/3.11.6/lib/python3.11/site-packages/irods/data_object.py", line 178, in close
    self.conn.close_file(self.desc, **self.options)
  File "/home/qubix/.pyenv/versions/3.11.6/lib/python3.11/site-packages/irods/connection.py", line 667, in close_file
    self.recv()
  File "/home/qubix/.pyenv/versions/3.11.6/lib/python3.11/site-packages/irods/connection.py", line 144, in recv
    raise NetworkException("Could not receive server response")
irods.exception.NetworkException: Could not receive server response
ERROR:irods.connection:Unable to send message. Connection to remote host may have closed. Releasing connection from pool.
Exception ignored in: <function Connection.__del__ at 0x7f183a36ed40>
Traceback (most recent call last):
  File "/home/qubix/.pyenv/versions/3.11.6/lib/python3.11/site-packages/irods/connection.py", line 109, in __del__
  File "/home/qubix/.pyenv/versions/3.11.6/lib/python3.11/site-packages/irods/connection.py", line 322, in disconnect
  File "/home/qubix/.pyenv/versions/3.11.6/lib/python3.11/site-packages/irods/connection.py", line 125, in send
irods.exception.NetworkException: Unable to send message
ERROR:irods.connection:Unable to send message. Connection to remote host may have closed. Releasing connection from pool.
  0%|                                                                                          | 0.00/10.0G [13:22<?, ?B/s]
ERROR:irods.connection:Unable to send message. Connection to remote host may have closed. Releasing connection from pool.
```

**Comment by qubixes** [comment]
A workaround for now would be to increase the `connection_timeout` parameter. It seems to be working if you increase this sufficiently.

**Comment by chStaiger** [comment]
I have another idea, let's write a upload_big_data and download_big_data function:

1. Create a local checksum
2a. Upload the file only (no checksum) with a higher `connecttion_timeout`
2b. Register the local cheksum in iRODS under: ibridges_local_checksum
3. Once  the upload is finished register the object's checksum in iRODS
4. Compare obj.checksum == ibridges_local_checksum

Steps 1 and 2 would go into the upload function and then steps 3 and 4 would go into a verify function.

@qubixes what do you think?
